#This could probably be done better with metaprogramming
import osproc

var salt_list : seq[string] = @[]
let output = open("websalt.nim", fmWrite)

#Readlines
for entry in lines("salt.txt"):
  salt_list.add(entry)

#The text of the source file to be created
let text = "#Generated by generate.nim\nimport dom, random, times, strutils\nproc onLoad() {.exportc.} =\n  const list = " & $salt_list[3..<len(salt_list)] & "\n  let time = ($(epochTime()))\n  randomize((time[4..len(time)-1].parseFloat * 100).int and 0xFFFFFFFF)\n  var content = list[rand(0..<len(list))]\n  document.getElementById(\"main\").innerHTML = content"

output.write(text)
output.close

#Compile websalt.nim to websalt.js
discard execCmd("nim js -d:release -o:public/websalt.js websalt.nim")

#This can probably be done better
#Get the contents of the file
var js_file = open("public/websalt.js", fmRead)
var js_list : seq[string] = @[]
for entry in lines(js_file):
  js_list.add(entry)
js_file.close()

#Prepare to rewrite the file with some additions
js_file = open("public/websalt.js", fmWrite)

#A tribute to the Father and a link to the source code
js_list[2] = "/* For Father Pohl */\n/* https://gitlab.com/websalt/websalt */\n"

#Write to the file and close it
for entry in js_list:
  js_file.write(entry & "\n")
js_file.close()

